apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-tracking-cm
  namespace: mlflow
data:
  MLFLOW_S3_ENDPOINT_URL: "https://<object_storage_namespace>.compat.objectstorage.<object_storage_region>.oraclecloud.com"
  BUCKET_URL: "s3://ml_bucket_mlflow"
  MYSQL_HOST: "<database_ip>"
  MYSQL_PORT: "3306"
  DB_NAME: "mlflow"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-deploy
  namespace: mlflow 
spec:
  selector:
    matchLabels:
      app: mlflow-tracking
  replicas: 2
  template:
    metadata:
      labels:
        app: mlflow-tracking
    spec:
      containers:
      - name: mlflow-tracking
        image: <region-key>.ocir.io/<tenancy-namespace>/<repo-name>:<tag>
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "2"
        env: 
        - name: MLFLOW_S3_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              name: mlflow-tracking-cm
              key: MLFLOW_S3_ENDPOINT_URL
        - name: BUCKET_URL
          valueFrom:
            configMapKeyRef:
              name: mlflow-tracking-cm
              key: BUCKET_URL
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mlflow-tracking-cm
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mlflow-tracking-cm
              key: MYSQL_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mlflow-tracking-cm
              key: DB_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-tracking-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-tracking-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-tracking-secret
              key: MYSQL_USER
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: mlflow-tracking-secret
              key: MYSQL_PWD
      imagePullSecrets:
      - name: <ocirsecret-name>
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-svc
  namespace: mlflow
spec:
  selector:
    app: mlflow-tracking
  ports:
    - port: 8088
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-tracking-ing
  namespace: mlflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: mlflow-tracking-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /tracking(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: mlflow-tracking-svc
              port:
                number: 8088
                